
development:
  adapter: postgresql
  encoding: unicode
  database: social-network-development-db
  pool: 5
  host: localhost
  username: postgres
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: social-network-test-db
  pool: 5
  host: localhost
  username: postgres
  password: admin

production:
  adapter: postgresql
  encoding: unicode
  database: social-network-production-db
  pool: 5
  username: postgres
  password: admin